name: Pipeline

on:
    push:
        branches: [main, docker]
    pull_request:
        branches: [main]
env:
  REGESRTY: ghcr.io
  IMAGE_NAME: troshxa/somemathfuncs
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust 
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
        
      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Linting
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test --verbose 
  build_and_push_docker:
    needs: build_and_test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGESRTY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGESRTY }}/${{ env.IMAGE_NAME }}:latest

  pull_docker:
    needs: build_and_push_docker
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGESRTY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ env.REGESRTY }}/${{ env.IMAGE_NAME }}:latest

        




    
    

